### ISSUE TITLE
Cannot read property 'ref' of undefined

### ISSUE THREAD

**Issue by Alireza29675** [leefsmp/Re-Flex#161]
Hey! I hope you're doing great!

This is the error that I'm facing:
```
TypeError: Cannot read properties of undefined (reading 'ref')
    at ReflexContainer.getSize (ReflexContainer.js:232:1)
    at ReflexContainer.computeAvailableStretch (ReflexContainer.js:362:1)
    at ReflexContainer.computeAvailableOffset (ReflexContainer.js:323:1)
    at ReflexContainer.js:108:1
    at new Promise (<anonymous>)
    at ReflexEvents.<anonymous> (ReflexContainer.js:101:1)
    at ReflexEvents.emit (ReflexEvents.js:55:1)
    at ReflexElement.componentDidUpdate (ReflexElement.js:111:1)
    at commitLifeCycles (react-dom.development.js:22117:1)
    at commitLayoutEffects (react-dom.development.js:25344:1)
```

And it is happening only when the container and elements get initialized and one element has initial size.

> I have two elements with a splitter between and I want the second element to have an initial size but it won't set and it logs this error. (Can it be thrown so I can handle it somewhere at least? console.log is not fair😄)

I put the `windowResizeAware` prop on the container and the interesting point is that when the window gets resized the second element will adopt its correct size. I'm really confused btw.

**Comment by leefsmp** [comment]
Can you take a look at #101 see if that helps first. Thanks.

**Comment by Alireza29675** [comment]
Looked for the closed issues but missed this one! Thank you, Philippe 🍻
