### ISSUE TITLE
Problem installing v4.0.11 on Yarn

### ISSUE THREAD

**Issue by akphi** [leefsmp/Re-Flex#183]
Hi @leefsmp,

I just tried to upgrade from v4.0.9 to v4.0.11 and bumped into the following error

```
# This file contains the result of Yarn building a package (node-sass@npm:4.14.1)
# Script name: postinstall

Building: /Users/anonymous/.nvm/versions/node/v16.18.0/bin/node /Users/anonymous/legend/studio/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/Users/anonymous/.nvm/versions/node/v16.18.0/bin/node',
gyp verb cli   '/Users/anonymous/legend/studio/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.18.0 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/anonymous/legend/studio/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/anonymous/legend/studio/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/anonymous/legend/studio/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/anonymous/legend/studio/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/anonymous/legend/studio/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/anonymous/legend/studio/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/Users/anonymous/legend/studio/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/anonymous/legend/studio/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/anonymous/legend/studio/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/Users/anonymous/legend/studio/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/anonymous/legend/studio/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/anonymous/legend/studio/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/anonymous/legend/studio/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/Users/anonymous/legend/studio/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/anonymous/legend/studio/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/Users/anonymous/legend/studio/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/Users/anonymous/legend/studio/node_modules/which/which.js:80:29)
gyp ERR! stack     at /Users/anonymous/legend/studio/node_modules/which/which.js:89:16
gyp ERR! stack     at /Users/anonymous/legend/studio/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /Users/anonymous/legend/studio/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:202:21)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/anonymous/.nvm/versions/node/v16.18.0/bin/node" "/Users/anonymous/legend/studio/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/anonymous/legend/studio/node_modules/node-sass
gyp ERR! node -v v16.18.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
```

I suppose this happens because we're using a fairly `node-sass`, but asides, I'm not sure what has changed since `4.0.9`, perhaps something about the fact that we updated the `package-lock.json` file?

Also, perusing the `package.json` file, I think we should move `node-sass` to `devDependencies` instead.

Lastly, I tried to do this myself locally, but I bumped into authentication a problem while trying to do `npm install`, I noticed that in `package-lock.json` we have a bunch of entries like

```
https://moicon-234774108989.d.codeartifact.eu-west-1.amazonaws.com:443/npm/main/isstream/-/isstream-0.1.2.tgz
```

probably because the lock file was created/updated behind some sort of NPM proxy, could you please take a look here?

Thank you so much, for now I'll keep ours at `4.0.9`

**Comment by leefsmp** [comment]
let me know if `v 4.0.12` fixes the issue on your side.

**Comment by akphi** [comment]
@leefsmp looks like it did. Also, I no longer found `node-sass` in my lock file after installation, that's nice! Did you move it out of `dependencies`?
